#!/usr/bin/env python3
"""Pack the desktop's ten approved illustrations for the round dial.

Five bounded, independently decoded layers keep animation small: rear, body,
front, expression and held mail. No runtime drawing or desktop assets on USB.
"""
from pathlib import Path
import hashlib
import importlib.util
import json
import zlib
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[4]
SOURCE = ROOT / 'daemons/tools/illustrated/daemon_art.py'
OUT = Path(__file__).resolve().parents[1] / 'assets/companions'
spec = importlib.util.spec_from_file_location('daemon_art', SOURCE)
art = importlib.util.module_from_spec(spec)
spec.loader.exec_module(art)
SIZES = (240, 108)
ROLES = ('rear', 'body', 'front', 'face', 'letter')
blob, memo, blocks = bytearray(), {}, []
capacities = [0] * len(ROLES)


def asset(image, size, role):
    image = image.resize((size, size), Image.Resampling.LANCZOS)
    box = image.getchannel('A').getbbox() or (0, 0, 1, 1)
    image = image.crop(box)
    pixels = list(image.get_flattened_data())
    # CO5300 panel order: high byte first, then one straight alpha plane.
    rgb = [((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3) for r, g, b, a in pixels]
    raw = b''.join(p.to_bytes(2, 'big') for p in rgb) + bytes(p[3] for p in pixels)
    digest = hashlib.sha256(raw).hexdigest()
    if digest not in memo:
        packed = zlib.compress(raw, 9)
        memo[digest] = (len(blob), len(packed))
        blob.extend(packed)
    offset, length = memo[digest]
    capacities[role] = max(capacities[role], len(raw))
    row = (offset, length, image.width, image.height, box[0], box[1], role)
    blocks.append(dict(offset=offset, length=length, raw=len(raw), sha256=digest))
    return row


def envelope():
    image = Image.new('RGBA', (192, 192))
    d = ImageDraw.Draw(image)
    d.rounded_rectangle((12, 33, 180, 147), 15, '#fff0cb', '#b79b69', 6)
    d.line([(21, 45), (96, 96), (171, 45)], '#b79b69', 6, joint='curve')
    d.line([(21, 138), (69, 93)], '#d2b785', 3)
    d.line([(171, 138), (123, 93)], '#d2b785', 3)
    return image


def c_array(name, dimensions, rows):
    def encode(value):
        return '{' + ','.join(str(v) if isinstance(v, int) else encode(v) for v in value) + '}'
    return f'static const companion_asset_t {name}{dimensions} = ' + encode(rows) + ';'


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    bodies, parts, faces, letters, anchors = [], [], [], [], []
    for size in SIZES:
        body_rows, part_rows, face_rows, anchor_rows = [], [], [], []
        for daemon in art.IDS:
            body_rows.append(asset(art.render_layers(daemon)['body'], size, 1))
            groups = []
            for group in range(4):
                phases = []
                for fraction in (0, .5, 1, .5):
                    layers = art.render_layers(daemon, pose=group * 2 + fraction)
                    phases.append([asset(layers['rear'], size, 0), asset(layers['front'], size, 2)])
                groups.append(phases)
            part_rows.append(groups)
            expressions = []
            for expression in art.EXPRESSIONS:
                expressions.append([asset(art.render_layers(daemon, expression=expression,
                    look=0 if expression == 'listening' else variant - 2,
                    level=variant if expression == 'listening' else 0)['face'], size, 3)
                    for variant in range(5)])
            face_rows.append(expressions)
            anchor_rows.append([round(v * size / art.SIZE) for v in art.LETTER_ANCHORS[daemon]])
        bodies.append(body_rows)
        parts.append(part_rows)
        faces.append(face_rows)
        anchors.append(anchor_rows)
        letters.append(asset(envelope(), round(64 * size / art.SIZE), 4))
    header = ['/* Generated by scripts/gen_companion_art.py; do not edit. */', '#pragma once',
        '#include <stdint.h>',
        'typedef struct { uint32_t offset, length; uint16_t width, height; int16_t x, y; uint8_t role; } companion_asset_t;',
        'enum { COMPANION_COUNT=10, COMPANION_ROLES=5, COMPANION_FRAMES=24 };',
        'static const uint32_t companion_capacity[5] = {' + ','.join(map(str, capacities)) + '};',
        'static const uint16_t companion_duration[8] = {150,90,140,55,180,220,35,125};',
        c_array('companion_bodies', '[2][10]', bodies),
        c_array('companion_parts', '[2][10][4][4][2]', parts),
        c_array('companion_faces', '[2][10][9][5]', faces),
        c_array('companion_letters', '[2]', letters),
        'static const int16_t companion_letter_anchor[2][10][2] = ' +
            str(anchors).replace('[', '{').replace(']', '}') + ';']
    (OUT / 'companion_art.h').write_text('\n'.join(header) + '\n')
    (OUT / 'companion_art.pack').write_bytes(blob)
    manifest = dict(format='zlib(RGB565BE + alpha8)', species=art.IDS, sizes=SIZES,
        source_sha256=hashlib.sha256(SOURCE.read_bytes()).hexdigest(), bytes=len(blob),
        sha256=hashlib.sha256(blob).hexdigest(), cache_bytes=sum(capacities), unique_blocks=len(memo))
    (OUT / 'manifest.json').write_text(json.dumps(manifest, indent=2) + '\n')
    for block in blocks:
        raw = zlib.decompress(blob[block['offset']:block['offset'] + block['length']])
        assert len(raw) == block['raw'] and hashlib.sha256(raw).hexdigest() == block['sha256']
    assert len(blob) < 5 * 1024 * 1024, 'Must fit both OTA slots with firmware and fonts.'
    print(json.dumps(manifest))


if __name__ == '__main__':
    main()
