#!/usr/bin/env python3
"""The Claude Code pet on the Focus agent screen: pixel art that stands in for the static mark.

    python3 devices/harness-device/firmware/scripts/gen_claude_pet.py          # write
    python3 devices/harness-device/firmware/scripts/gen_claude_pet.py --check  # fail if stale

A 12 x 8 cell sprite at CELL px per cell, plus one spare row on top: 60 x 45 px per frame. Each state
(idle, working, done, asking) is a loop of 24 steps, each a frame and a vertical offset in px, on the
Pro daemons' clock. Frames are de-duplicated, so the file holds each pose once and the loops index it.
Writes main/ui/habitat/claude_pet.c: ht_claude_pet_frames, ht_claude_pet_loops, ht_claude_pet_step_ms
(declared in claude_pet.h). Frames use the same encoding as gen_focus_marks.py: RGB565 in panel order
plus alpha8 (0 or 255 only).
"""
import sys
from pathlib import Path

from PIL import Image, ImageDraw

root = Path(__file__).resolve().parents[1]
CELL = 5
W, H = 12 * CELL, 9 * CELL
STEPS = 24
BODY = (204, 120, 92)
EYE = (0, 0, 0)
LEGS = (2, 4, 7, 9)                  # leg columns
STEP_MS = (150, 90, 55, 140)         # idle, working, done, asking


def sprite(eyes='open', arms=0, legs=(2, 2, 2, 2), look=0):
    """One pose as {(col, row): colour}. arms: 0 level, -1 raised one row. legs: rows per leg."""
    cells = {}
    for r in range(6):
        for c in range(2, 10):
            cells[(c, r)] = BODY
    for r in (2 + arms, 3 + arms):
        for c in (0, 1, 10, 11):
            cells[(c, r)] = BODY
    for c, n in zip(LEGS, legs):
        for r in range(6, 6 + n):
            cells[(c, r)] = BODY
    if eyes == 'open':
        cells[(3 + look, 1)] = EYE
        cells[(8 + look, 1)] = EYE
    elif eyes == 'happy':            # ^ ^ : the eye cell lifted a row
        for c in (3, 8):
            cells[(c, 0)] = EYE
    return cells                     # 'closed' leaves the eyes as body


def idle():
    bob = (0,) * 6 + (1,) * 6 + (0,) * 6 + (1,) * 6
    return [(sprite('closed' if i in (20, 21) else 'open'), bob[i]) for i in range(STEPS)]


def working():
    out = []
    for i in range(STEPS):
        phase = (i // 3) % 4
        legs = [(2, 1, 2, 1), (2, 2, 2, 2), (1, 2, 1, 2), (2, 2, 2, 2)][phase]
        look = ([0] * 6 + [1] * 6 + [0] * 6 + [-1] * 6)[i]
        out.append((sprite('open', 0, legs, look), 0 if phase in (1, 3) else -1))
    return out


def done():
    hop = (0, -1, -2, -3, -4, -4, -3, -2, -1, 0, 0, 0)
    out = []
    for i in range(STEPS):
        if i < 12:
            arms = -1 if hop[i] < -1 else 0
            legs = (2, 2, 2, 2) if hop[i] == 0 else (1, 1, 1, 1)
            out.append((sprite('happy', arms, legs), hop[i] * CELL // 2))
        else:
            out.append((sprite('happy' if i < 20 else 'open'), 0))
    return out


def asking():
    return [(sprite('open', -1 if (i // 4) % 2 == 0 else 0), 0) for i in range(STEPS)]


def render(cells):
    """Row r at y = (r + 1) * CELL: the spare row on top is for the hop."""
    im = Image.new('RGBA', (W, H), (0, 0, 0, 0))
    d = ImageDraw.Draw(im)
    for (c, r), col in cells.items():
        y = r * CELL + CELL
        d.rectangle([c * CELL, y, c * CELL + CELL - 1, y + CELL - 1], fill=col)
    return im


def emit(name, img):
    px, alpha = [], []
    for r, g, b, a in img.get_flattened_data():
        v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
        px.append(((v << 8) | (v >> 8)) & 0xFFFF)
        alpha.append(255 if a else 0)
    return (f'static const uint16_t {name}_px[] = {{' + ','.join(map(str, px)) + '};\n'
            f'static const uint8_t {name}_a[] = {{' + ','.join(map(str, alpha)) + '};\n',
            f'{{{W},{H},{name}_px,{name}_a}}')


def generate():
    frames, index, loops = [], {}, []
    for state in (idle, working, done, asking):
        steps = []
        for cells, dy in state():
            key = tuple(sorted(cells.items()))
            if key not in index:
                index[key] = len(frames)
                frames.append(cells)
            steps.append((index[key], dy))
        loops.append(steps)
    out = ['// Generated by scripts/gen_claude_pet.py. Do not edit.\n'
           '// The Claude Code pet: de-duplicated frames and the idle/working/done/asking loops.\n'
           '#include "claude_pet.h"\n']
    refs = []
    for n, cells in enumerate(frames):
        code, ref = emit(f'pet{n}', render(cells))
        out.append(code)
        refs.append(ref)
    out.append(f'const unsigned ht_claude_pet_frame_count = {len(frames)};\n')
    out.append(f'const ht_icon_t ht_claude_pet_frames[{len(frames)}] = {{' + ','.join(refs) + '};\n')
    rows = ['{' + ','.join(f'{{{f},{dy}}}' for f, dy in steps) + '}' for steps in loops]
    out.append('const ht_pet_step_t ht_claude_pet_loops[HT_PET_STATES][HT_PET_STEPS] = {' + ','.join(rows) + '};\n')
    out.append('const uint16_t ht_claude_pet_step_ms[HT_PET_STATES] = {' + ','.join(map(str, STEP_MS)) + '};\n')
    return ''.join(out), len(frames)


def main():
    text, count = generate()
    target = root / 'main/ui/habitat/claude_pet.c'
    if '--check' in sys.argv[1:]:
        if not target.exists() or target.read_text() != text:
            print(f'{target} is stale: run scripts/gen_claude_pet.py', file=sys.stderr)
            return 1
        return 0
    target.write_text(text)
    print(f'{target}: {count} frames, {count * W * H * 3} bytes')
    return 0


if __name__ == '__main__':
    sys.exit(main())
