#!/usr/bin/env python3
"""Deterministic fixed-cell, 2-bit font atlases. Requires Pillow 12.2.0.

Geist Mono: SIL OFL, vendored beside Geist. Unscii-8: public domain, from LVGL 9.5.0.
No font engine runs on the ESP32. Regenerate from the repository root.
"""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont
root = Path(__file__).resolve().parents[1]
dest = root / 'main/ui/habitat/fonts.c'
mono = root / 'fonts/GeistMono-Regular.ttf'
pixel = root.parent / 'prototype/habitat/assets/unscii-8.ttf'
fonts = [('ht_mono_16',mono,16,10,22,17),('ht_mono_20',mono,20,12,28,22),
         ('ht_mono_24',mono,24,15,32,26),('ht_mono_28',mono,28,17,38,31),
         ('ht_pixel_40',pixel,40,40,48,40),('ht_open_20',mono,20,12,28,22),
         ('ht_lock_dot',pixel,40,40,48,40)]
with dest.open('w') as out:
    out.write('// Generated by scripts/gen_habitat_fonts.py. Do not edit.\n#include "terminal.h"\n')
    curved_bounds=[]
    for name,path,size,width,height,baseline in fonts:
        font=ImageFont.truetype(str(path),size)
        data=[]
        bounds=[]
        # Latin-1 keeps common names readable; unknown Unicode renders ?, never changes wire text.
        first,last=(0x2197,0x2197) if name=='ht_open_20' else (ord('o'),ord('o')) if name=='ht_lock_dot' else (32,255 if name!='ht_pixel_40' else 126)
        for cp in range(first,last+1):
            im=Image.new('L',(width,height));ImageDraw.Draw(im).text((0,baseline),chr(cp),font=font,fill=255,anchor='ls',stroke_width=0)
            values=[min(3,(v+42)//85) for v in im.get_flattened_data()]
            if name in ('ht_mono_20','ht_open_20'):
                ink=[(i%width,i//width) for i,a in enumerate(values) if a]
                bounds.append((min(x for x,y in ink),min(y for x,y in ink),
                               max(x for x,y in ink),max(y for x,y in ink)) if ink else (0,0,0,0))
            values += [0]*((-len(values))%4)
            data.extend(sum(values[j+k]<<(6-2*k) for k in range(4)) for j in range(0,len(values),4))
        out.write(f'static const uint8_t {name}_pixels[] = {{\n')
        for j in range(0,len(data),24):out.write('  '+','.join(map(str,data[j:j+24]))+',\n')
        out.write(f'}};\nconst ht_font_t {name} = {{{first},{last},{width},{height},{name}_pixels}};\n')
        print(f'{name}: {len(data)} bytes, {width} x {height} fixed cell')
        if bounds: curved_bounds.append((name,bounds))
    # These tiny immutable bounds let rotated labels skip transparent margins.
    # The actual atlas and interpolation stay unchanged; no runtime font engine.
    for name,bounds in curved_bounds:
        out.write(f'const uint8_t {name}_ink[{len(bounds)}][4] = {{\n')
        for b in bounds: out.write('  {'+','.join(map(str,b))+'},\n')
        out.write('};\n')
