"""Pack cached ElevenLabs PCM into the offline Pro audition library (Python 3.12).

No network or credentials. Original PCM stays in --audio-dir; samples.json and
samples.pack record the exact same recordings for every development device.
"""
import argparse
import hashlib
import json
import math
from pathlib import Path
import warnings
warnings.filterwarnings('ignore', category=DeprecationWarning)
import audioop

p = argparse.ArgumentParser()
p.add_argument('--manifest', type=Path, required=True)
p.add_argument('--audio-dir', type=Path, required=True)
p.add_argument('--out', type=Path, default=Path(__file__).resolve().parent.parent / 'voice-samples')
a = p.parse_args()
rows = json.loads(a.manifest.read_text())
pack = bytearray()
def c(s): return json.dumps(s, ensure_ascii=True)
lines = ['// Generated by tools/pack_voice_samples.py. No credentials.\n', 'static const pro_voice_sample_t voice_samples[] = {\n']
for row in rows:
    pcm = (a.audio_dir / row['pcm_file']).read_bytes()
    assert hashlib.sha256(pcm).hexdigest() == row['sha256']
    assert len(pcm) == row['samples'] * 2 and 0 < row['samples'] <= 16000 * 12
    encoded, _ = audioop.lin2adpcm(pcm, 2, None)
    decoded, _ = audioop.adpcm2lin(encoded, 2, None)
    assert len(decoded) == len(pcm) and len(encoded) == (row['samples'] + 1) // 2
    row['adpcm_offset'] = len(pack)
    row['adpcm_bytes'] = len(encoded)
    row['adpcm_sha256'] = hashlib.sha256(encoded).hexdigest()
    row['decoded_sha256'] = hashlib.sha256(decoded).hexdigest()
    row['storage_codec'] = 'IMA ADPCM / high nibble first / initial state 0,0'
    row['playback_gain'] = '4x tanh soft gain / 0.63 ceiling / fixed across samples'
    seed = -1 if row['seed'] is None else row['seed']
    fields = [c(row[k]) for k in ['id','voice','title','model_id','tag','caption','note','voice_id']]
    fields += [str(len(pack)),str(row['samples']),str(seed),str(round(row['stability']*100)),str(round(row['similarity_boost']*100))]
    lines.append('    {' + ', '.join(fields) + '},\n')
    pack.extend(encoded)
lines.append('};\nstatic const int16_t voice_gain[257] = {\n')
values = [round(32767 * .63 * math.tanh((n*128 / 32768) * 4 / .63)) for n in range(257)]
for at in range(0,len(values),16): lines.append('    '+','.join(map(str,values[at:at+16]))+',\n')
lines.append('};\n')
assert len(pack) < 700000, 'Preserve room in the existing OTA slot'
a.out.mkdir(parents=True,exist_ok=True)
(a.out/'samples.pack').write_bytes(pack)
(a.out/'pro_voice_samples.inc').write_text(''.join(lines))
(a.out/'samples.json').write_text(json.dumps(rows,indent=2)+'\n')
print(f'{len(rows)} samples / {len(pack)} bytes / {sum(r["seconds"] for r in rows):.2f} seconds')
print('pack SHA-256:',hashlib.sha256(pack).hexdigest())
